### ISSUE TITLE
codeceptjs peer dependency version

### ISSUE THREAD

**Issue by wadamek65** [pavkam/codeceptjs-browserlogs-plugin#2]
Hi,

The project has listed `"codeceptjs": "^2.6.8"` as a peerDependency. We've been using this plugin with versions 3 and above and it seems to work fine as well.

Could you please update the peerDependency version requirements to also include versions 3 and upward so that npm 7 doesn't show any errors during installation? Alternatively, would it be okay for you if I submitted a PR with this change?

**Comment by pavkam** [comment]
Hello,

Thanks for describing the issue.
Any PRs are welcome, so feel free to submit one.

Cheers,
Alex.
