### ISSUE TITLE
log message pollutes cli output

### ISSUE THREAD

**Issue by cjhille** [pavkam/codeceptjs-browserlogs-plugin#5]
I've been wondering about random "string" log messages showing up in cli after a test fails. Turns out it came from this [line](https://github.com/pavkam/codeceptjs-browserlogs-plugin/blob/ccdaa9ee42bffba1468cc16845d16a18bda97fc4/index.js#L201). I assume this wasn't by design.

**Comment by pavkam** [comment]
Fixed in https://github.com/pavkam/codeceptjs-browserlogs-plugin/pull/6

Thanks!
